#pragma once

enum class AE_Error {
	NONE = 0,
	OUT_OF_MEMORY = 4,
	INTERNAL_STRUCT_DAMAGED = 512,
	INVALID_INDEX,
	UNRECOGNIZED_PARAM_TYPE,
	INVALID_CALLBACK,
	BAD_CALLBACK_PARAM,
	Interrupt_CANCEL,
	CANNOT_PARSE_KEYFRAME_TEXT
};
